name: Deployment to Github/Gitee pages
on:
  push:
    branches:
      - master # 或者是你的主分支名
env:
  REACT_APP_DEPLOY_ENV: pages
permissions:
  contents: write # 必须赋予写权限才能推送到 gh-pages 分支
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.17.0]
    steps:
      - uses: actions/checkout@v4 # 升级到 v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 # 升级到 v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn' # 启用缓存加速构建
          
      - name: Install Packages
        run: yarn
        
      - name: Build page
        run: yarn build
        
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3 # 该插件目前 v3 仍可使用，关键是 checkout 和 setup-node 需要升级
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE }}
        with:
          source-repo: git@github.com:richarsceihs3352-cmyk/qwerty-learner.git
          destination-repo: git@gitee.com:richarsceihs3352-cmyk/qwerty-learner.git
